name: Assets

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  download-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: âš™ï¸ Install bsdtar
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-tools
          sudo apt-get install -y bsdtar
      - name: â¤µï¸ Get Age binary
        run: |
          ./.github/scripts/get-age-binary.sh
      - name: âœğŸ» Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Age binary
          title: Update Age binary
          body: |
            This PR updates the Age binary used by Devantler.AgeCLI to the latest version.
          branch: update-age-binary
          delete-branch: true
          labels: dependencies
          reviewers: devantler
          assignees: devantler
          signoff: true
